apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gpu-scheduler-webhook
webhooks:
  - name: gpu-shared.gpu-scheduler.io
    clientConfig:
      url: "https://localhost:8443/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lVQWtaem1OWFcxZVRnMlZCd1NUaXFaZWNoWTB3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF3d1FaM0IxTFhOamFHVmtkV3hsY2kxallUQWVGdzB5TmpBeU1qRXhPREF3TVROYQpGdzB6TmpBeU1Ua3hPREF3TVROYU1Cc3hHVEFYQmdOVkJBTU1FR2R3ZFMxelkyaGxaSFZzWlhJdFkyRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2lCY2lMSTVZdnRUMUtvV3RQalpCWG51bWMKV045WGdWVFhkYThKeitFcnlydTN0eTFvdXBCcGhWeHRFTFhJRkpLNURReUhZUzFtQXpkUWJ2eW1mNkFSSzRhYwp0Z1JzdG5la1Fwcm9HSTdWM1hSOG1DMzVXb3g0eGRDYk1aN0tveitxanV6MWpobUtubGxmZVdMUS9mVjlwcmk0CjlKYjN4dFNRWXAreUptT1hpQmNwL3FPdWdqc1pDWjRpQ1lIV1JXS2hYK3h5MDFZbnJSVGhiTWg2R1d2d2RqOXYKTFlmUVBvZi9rSWV0SVZramgvYTFwZitFR2FucCtBT3FtcTdRRm45N1FpMHl0Z2dGZjdIUGlqYVNHZzFYQ2huVgowWU9UU0NSOVJnVXo0MFhmYW1Rd0NZdFRGZzJxTnFEeDBVTDJ6TzVUOStDaHp5Ui9IRjdORW04Wmtnb1pBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRbEVZUjJ6djYzYTJmMVZxemQ2TzVNb210TlZEQWZCZ05WSFNNRUdEQVcKZ0JRbEVZUjJ6djYzYTJmMVZxemQ2TzVNb210TlZEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUFKZW5jdDJ3cVVVamlCRUFTQjFkWTZBTCtiMjQ5ZUtiWVhJekJFZ3FxOWI4d2hIcXZTCjd4TnNmMXBWQ2Q1SDUrb09lN1pkanBPZm5oRm45d2VQbnUvYnRyZzNTbkxZUGVSYXdUbTJqVVFKUUJRT3Z5TzUKOWFjMnBGSjk0L0RmanF6ZDNTVS9UZWc4YkEvbVV0ZWRxN3Q4OVFiMHF0SXRqajJ4eFdFSzhWRW55NkdXTURSRApJQkRMOHhMVDR4dEpCYS9NK0U0WmJXSm1ZRXZaZ1ZGb0h5KzFHQk15SFBycEcrdmNZQ1VKN1dUQXZRU3BxM1phCmQ2amJRUWV3UksvNndEM3h1cVZNME85Nkw0eVMvN21scTRud0V2dlZ5bk5pb09QcWEwSmEyRElSR3lHMlhiQXYKcHJEWStHcTZ2TEFSeG8wSUhkalN0c1JGMDhyQ3M5emZ5cnlKCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]
